import os
import math
from datetime import datetime
from typing import Dict, Any, List
try:
    import googlemaps
    gmaps_key = os.environ.get("GOOGLE_MAPS_API_KEY")
    gmaps = googlemaps.Client(key=gmaps_key) if gmaps_key else None
except Exception as e:
    print(f"Google Maps Client not initialized (Local Dev Mode): {e}")
    gmaps = None

from db.memory import _appointments, _patients, get_medicine_inventory_summary

def get_coordinates(location_name: str, region_context: str = "Maharashtra, India") -> dict:
    """
    Dynamically fetches precise lat/lng using Google Maps Geocoding.
    Fails gracefully if the API is unavailable.
    """
    if not gmaps:
        return None
        
    try:
        query = f"{location_name}, {region_context}"
        result = gmaps.geocode(query)
        if result:
            loc = result[0]['geometry']['location']
            return {"lat": loc['lat'], "lng": loc['lng']}
    except Exception as e:
        print(f"Geocoding failed for {location_name}: {e}")
    return None

def haversine_distance(coord1: dict, coord2: dict) -> float:
    """Calculates straight-line distance in kilometers."""
    R = 6371  # Earth radius in km
    lat1, lon1 = math.radians(coord1['lat']), math.radians(coord1['lng'])
    lat2, lon2 = math.radians(coord2['lat']), math.radians(coord2['lng'])
    
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    a = math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    return R * c

def detect_macro_clusters(anomalies: List[Dict]) -> List[Dict]:
    """
    Evaluates isolated anomalies generated by detect_spatial_anomalies. 
    If two distinct localities report the same critical symptom within 5km, 
    they are merged into a severe Regional Epidemic alert.
    """
    macro_clusters = []
    
    for i, anomaly1 in enumerate(anomalies):
        coord1 = anomaly1.get('coordinates')
        if not coord1: 
            continue

        for j, anomaly2 in enumerate(anomalies):
            if i >= j: continue  # Avoid self-comparison or duplicate checks
            
            # If the same symptom is triggering in both localities
            if anomaly1['symptom'] == anomaly2['symptom']:
                coord2 = anomaly2.get('coordinates')
                if coord2:
                    dist = haversine_distance(coord1, coord2)
                    
                    if dist <= 5.0:  # 5km threshold
                        macro_clusters.append({
                            "type": "REGIONAL_EPIDEMIC",
                            "symptom": anomaly1['symptom'],
                            "affected_zones": [anomaly1['locality'], anomaly2['locality']],
                            "distance_span_km": round(dist, 2),
                            "severity": "CRITICAL_ESCALATION"
                        })
    return macro_clusters

def find_surplus_clinics(target_medicine: str, exclude_facility: str) -> List[Dict]:
    """
    Dynamically scans memory.py to find facilities holding a positive balance of the medicine.
    """
    # Dynamically extract all unique facility IDs that have received stock
    from db.memory import _audit_events
    all_facilities = list(set([e.facility_id for e in _audit_events]))
    
    surplus_clinics = []
    for facility in all_facilities:
        if facility == exclude_facility: 
            continue
            
        inventory = get_medicine_inventory_summary(facility, target_medicine)
        
        # Buffer of 50 units ensures we don't route patients to a clinic that is about to run out
        if inventory["unaccounted"] > 50:
            # In a real DB, fetch address from Facility profile. 
            # Here, we dynamically construct a search string based on ID format.
            locality_str = "Bandra West" if "002" in facility else "Mumbai"
            surplus_clinics.append({
                "facility_id": facility,
                "address": locality_str,
                "surplus_stock": inventory["unaccounted"]
            })
            
    return surplus_clinics

def find_emergency_clinic_route(depleted_facility_id: str, depleted_locality: str, needed_medicine: str) -> Dict:
    """
    Full logistics pipeline: Finds who has stock, then calculates the fastest live route.
    """
    if not gmaps:
        return {"error": "Google Maps API key not configured for live routing."}

    available_clinics = find_surplus_clinics(needed_medicine, depleted_facility_id)
    
    if not available_clinics:
        return {"error": f"Critical stockout. No facilities possess {needed_medicine}."}
        
    origin_address = f"{depleted_locality}, Maharashtra, India"
    destination_addresses = [f"{c['address']}, Maharashtra, India" for c in available_clinics]
    
    try:
        matrix = gmaps.distance_matrix(
            origins=[origin_address],
            destinations=destination_addresses,
            mode="driving",
            departure_time="now" 
        )
        
        best_route = None
        shortest_time = float('inf')
        
        for i, element in enumerate(matrix['rows'][0]['elements']):
            if element['status'] == 'OK':
                duration_seconds = element['duration']['value']
                
                if duration_seconds < shortest_time:
                    shortest_time = duration_seconds
                    best_route = {
                        "redirect_to_facility": available_clinics[i]['facility_id'],
                        "destination_address": available_clinics[i]['address'],
                        "available_stock": available_clinics[i]['surplus_stock'],
                        "driving_time_mins": int(duration_seconds / 60),
                        "distance_text": element['distance']['text']
                    }
                    
        return best_route
        
    except Exception as e:
        print(f"Distance Matrix API Failed: {e}")
        return {"error": "Routing engine temporarily unavailable."}

def detect_spatial_anomalies(days_back: int = 7, anomaly_threshold: int = 3) -> Dict[str, Any]:
    """
    Upgraded Feature 4: Scans appointments, aggregates by locality, appends Geocoding, 
    and checks for regional epidemic escalation.
    """
    spatial_map: Dict[str, Dict[str, int]] = {}
    
    for apt in _appointments:
        patient = next((p for p in _patients if p.patient_id == apt.patient_id), None)
        locality = patient.locality if patient else "UNKNOWN_REGION"
        
        if locality not in spatial_map:
            spatial_map[locality] = {}
            
        for symptom in apt.symptoms:
            s_lower = symptom.lower().strip()
            spatial_map[locality][s_lower] = spatial_map[locality].get(s_lower, 0) + 1

    anomalies = []
    for locality, symptoms in spatial_map.items():
        # Dynamically grab coordinates once per anomalous locality
        coords = get_coordinates(locality) if locality != "UNKNOWN_REGION" else None

        for symptom, count in symptoms.items():
            if count >= anomaly_threshold:
                severity = "CRITICAL" if count >= (anomaly_threshold * 2) else "WARNING"
                
                anomalies.append({
                    "locality": locality,
                    "coordinates": coords,  # Added for Map Rendering
                    "symptom": symptom,
                    "case_count": count,
                    "threshold_exceeded": anomaly_threshold,
                    "severity": severity,
                    "status": "ACTIVE",
                    "action_recommended": f"Dispatch rapid response unit to {locality} to investigate {symptom} cluster."
                })

    # Run the Macro-Cluster check using the haversine formula
    macro_clusters = detect_macro_clusters(anomalies)

    return {
        "scan_timestamp": datetime.utcnow().isoformat(),
        "total_localities_scanned": len(spatial_map),
        "active_anomalies": anomalies,
        "regional_epidemic_escalations": macro_clusters, # NEW: The intelligent grouping
        "raw_spatial_data": spatial_map 
    }